<a href="https://colab.research.google.com/github/sitthatkaja/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## **Numpy**
- สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## **matrix transpose**

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## **สร้าง Matrix เริ่มต้น (Zeros,one)**

In [8]:
np_z = np.zeros((4,5))

In [9]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##  **สร้าง matrix random**

In [12]:
np_random = np.random.randn(5,5)
np_random

array([[ 1.05670859,  0.14660205,  1.38646316, -0.3258006 , -1.20987296],
       [-0.44392702, -0.42803874, -0.61107618,  1.73618238, -1.32519683],
       [-0.95954339,  0.37288764,  2.12894533, -2.54383101,  1.58886562],
       [ 0.40322945,  0.64735353,  1.06519814,  0.52499913,  1.77583543],
       [-1.88438425, -1.3098514 ,  0.63389649,  0.14424622,  0.05740389]])

In [13]:
2 + (5*np.random.randn(3,3))

array([[-1.71101241,  3.88630119, 10.71379036],
       [-0.61712387, -2.30169619, -2.08211937],
       [ 4.21648452, -1.77925534,  4.85674036]])

- random(int)

In [14]:
np.random.randint(5,11,(4,5))

array([[ 8,  7,  9,  5,  5],
       [ 7, 10, 10,  7,  8],
       [ 7,  6,  9,  8,  8],
       [ 7,  8,  5,  5,  5]])

matrix properties

In [15]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
1 + np_a

array([[2, 3, 4],
       [5, 6, 7]])

In [18]:
2 * np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [19]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [20]:
np_a + np_c

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:

np_a.shape

(2, 3)

In [22]:
np_c.shape

(2, 3)

In [23]:
np_c.T.shape

(3, 2)

In [24]:
np.dot(np_a,np_c.T) 

array([[28, 10],
       [73, 28]])


Indexing & Slicing

In [25]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np_a[1,1]

5

In [27]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [28]:
np_a[0,:]

array([1, 2, 3])

Useful functions

In [29]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:

np.sum(np_a)

21

In [31]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [32]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [33]:
np.mean(np_a)

3.5

In [34]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

วนลูปเอง


summation

In [35]:
np_a.shape

(2, 3)

In [36]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


In [37]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


วากาเมะ ข้อ 9 

วนลูปหาค่า np.min(np.a,axis=0)

In [57]:
np.min(np_a,axis=0)

array([1, 2, 3])

In [60]:
min = np.zeros(np_a.shape[1])

for row in range(np_a.shape[1]):
   min[row] = min(np_a[row])
print(min)

TypeError: ignored