<a href="https://colab.research.google.com/github/sitthatkaja/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## **Numpy**
- สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## **matrix transpose**

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## **สร้าง Matrix เริ่มต้น (Zeros,one)**

In [8]:
np_z = np.zeros((4,5))

In [9]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

##  **สร้าง matrix random**

In [12]:
np_random = np.random.randn(5,5)
np_random

array([[-0.00821635, -2.35751052,  1.16488484,  0.0652555 , -0.19873152],
       [-1.42447067, -0.65548317,  0.65159453,  0.00801407,  1.00074737],
       [ 1.94809715, -1.20223039,  1.28428241,  0.68566806, -1.68343232],
       [ 0.25891563, -0.94726151,  1.98410104, -1.22010212, -0.13983875],
       [ 0.24791108, -1.37983849, -0.5564029 ,  1.05639125,  1.06886299]])

In [13]:
2 + (5*np.random.randn(3,3))

array([[ 6.19936925,  6.47676535, -0.20525619],
       [ 2.92293233,  5.4607836 , -1.76909677],
       [ 4.2023444 , -5.66174265, 16.65906673]])

- random(int)

In [14]:
np.random.randint(5,11,(4,5))

array([[ 9,  9,  8,  7, 10],
       [ 7, 10, 10,  7,  9],
       [ 7,  9,  5,  5,  9],
       [ 6, 10,  8,  5,  5]])